sudo: false
git:
  depth: 1
branches:
  only:
  - master
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install flake8
  - pip install pep257
# command to run tests
script:
  - flake8 . --max-line-length=120 --ignore=D211
  - pep257 . --ignore=D202,D211
notifications:
  email: false