version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "linter.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 pep257

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "linter.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 . --max-line-length=120 --ignore=D211
            pep257 . --ignore=D202,D211

      - store_artifacts:
          path: test-reports
          destination: test-reports
